"""empty message

Revision ID: 277c8356f3b9
Revises: 38de47a66f12
Create Date: 2019-08-07 08:49:06.789704

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '277c8356f3b9'
down_revision = '38de47a66f12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accommodation', sa.Column('standard_guess', sa.Integer(), nullable=False))
    op.alter_column('accommodation', 'address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('accommodation', 'apartment_manual',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('accommodation', 'apartment_rule',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('accommodation', 'checkin_guide',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('accommodation', 'description',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('accommodation', 'direction_manual',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('accommodation', 'member_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    op.alter_column('accommodation', 'num_bathrooms',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=True)
    op.alter_column('accommodation', 'num_bedrooms',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=True)
    op.alter_column('accommodation', 'num_beds',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=True)
    op.alter_column('accommodation', 'property_type_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('accommodation', 'room_type_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('accommodation', 'special_notices',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('property_type', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property_type', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('accommodation', 'special_notices',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('accommodation', 'room_type_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('accommodation', 'property_type_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('accommodation', 'num_beds',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=False)
    op.alter_column('accommodation', 'num_bedrooms',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=False)
    op.alter_column('accommodation', 'num_bathrooms',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=False)
    op.alter_column('accommodation', 'member_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    op.alter_column('accommodation', 'direction_manual',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('accommodation', 'description',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('accommodation', 'checkin_guide',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('accommodation', 'apartment_rule',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('accommodation', 'apartment_manual',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('accommodation', 'address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('accommodation', 'standard_guess')
    # ### end Alembic commands ###
