"""empty message

Revision ID: 38de47a66f12
Revises: a40f488be636
Create Date: 2019-08-07 08:08:10.627574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38de47a66f12'
down_revision = 'a40f488be636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('member_id', sa.String(length=32), nullable=True))
    op.create_foreign_key(None, 'image', 'member', ['member_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.drop_column('image', 'member_id')
    # ### end Alembic commands ###
