"""empty message

Revision ID: a40f488be636
Revises: 639f004a4d05
Create Date: 2019-08-06 15:49:02.841110

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a40f488be636'
down_revision = '639f004a4d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'accommodation_id',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.drop_column('image', 'member_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('member_id', mysql.VARCHAR(length=32), nullable=True))
    op.alter_column('image', 'accommodation_id',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###
